config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "groups#index"
  resources :users, only: [:edit, :update, :index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :messages

  def show_last_message
    if (last_message = messages.last).present?
      last_message.comment? ? last_message.comment : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :comment, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :members
  has_many :groups, through: :members
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    @new_messages = @group.messages.where('id > ?', params[:lastMessage])
      respond_to do |format|
        format.html
        format.json
      end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください'
      render :text => "error", :status => 500
    end
  end

  private
  def set_group
    @group = Group.find(params[:group_id])
  end

  def message_params
    params.require(:message).permit(:comment, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:name]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: "グループ名を入力してください"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input.chat-group-form__input{id: 'user-search-field', placeholder: '追加したいユーザー名を入力してください', type: 'text'}
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users
        - group.users.each do |member|
          .chat-group-user.clearfix.js-chat-member
            %input{name: 'group[user_ids][]', type: 'hidden', value: "#{member.id}"}
            %p.chat-group-user__name
              = member.name
            %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
              削除
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
= javascript_include_tag 'search.js'

.chat-group-form
  %h1 チャットグループ編集
  = render 'form', { group: @group }

app/views/groups/index.html.haml
.wrapper

  = render 'layouts/side_bar'

app/views/groups/new.html.haml
= javascript_include_tag 'search.js'

.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_side_bar.html.haml
.sidebar
  .sidebar__user-menu
    %p.sidebar__user-menu__user-name
      = current_user.name
    %a.sidebar__user-menu__list
      = link_to edit_user_path(current_user) do
        = fa_icon "cog", class: 'sidebar__user-menu__edit-link'
    %a.sidebar__user-menu__list
      = link_to new_group_path do
        = fa_icon "pencil-square-o", class: 'sidebar__user-menu__new-link'
  .sidebar__group-list
    - current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        .sidebar__group-list__title
          = group.name
        .sidebar__group-list__comment
          = group.show_last_message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_message.html.haml
.chat-main__content__message-block{data: {id: message.id} }
  %p.chat-main__content__message-block__name
    = message.user.name
  %p.chat-main__content__message-block__time
    = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  - if message.comment.present?
    %p.chat-main__content__message-block__text
      = message.comment
  .chat-main__content__message-block__picture
  = image_tag message.image.url, class: "chat-main__content__message-block__image" if message.image.present?

app/views/messages/index.html.haml
= javascript_include_tag 'message.js'

= render "layouts/side_bar"

/ mainview
.chat-main
  .chat-main__header
    %p.chat-main__header__group-name
      = @group.name
    = link_to 'Edit', 'edit', class: "chat-main__header__edit-button"
    %p.chat-main__header__group-member
      Members:
      - @group.members.each do |member|
        = member.user.name
  .chat-main__content
    = render partial: 'message', collection: @messages
  .chat-main__footer
    .chat-main__footer__form
      = form_for [@group, @message] do |f|
        = f.text_field :comment, class: "chat-main__footer__form__message-form", placeholder: "type a message"
        = f.label :image, class: "chat-main__footer__form__label", for: "icon" do
          = fa_icon 'picture-o', class: "chat-main__footer__form__picture"
          = f.file_field :image, class: "chat-main__footer__form__label__file", id: "icon"
        = f.submit 'Send', class: "chat-main__footer__form__send-button"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'